### ISSUE TITLE
Artifact style

### ISSUE THREAD

**Issue by Eceri** [Eceri/KR-Index#1]
Artifacts need some restyling. Juno's Special Dessert has text overflows. Maybe use tabs to separete Story and Effect of the Artifact.

**Comment by LLath** [comment]
First try was to implement tabs for Effect and Story of a Artifact.

![image](https://user-images.githubusercontent.com/3504160/70747248-ddc7a480-1d27-11ea-93aa-a98b3e9d3b62.png)
