### ISSUE TITLE
Add BiS (Best in Slot) for Hero

### ISSUE THREAD

**Issue by vmwinckler** [Eceri/KR-Index#11]
**Best in Slot(BiS) for all situations or for especifc instance:**

1. Best Artifact
2. Best order for Unique Treasures: 1st and 3 others
3. Best Final equip (Lava, Black Dragon, Dark Legion...)

**Comment by LLath** [comment]
Hi
thanks for opening an issue.

Where would you want to find this information ?

Should it be like a written Guide or just some bullet points ?

Where can we get this information ?

**Comment by NamSPro** [comment]
In my opinion,
These information should be collected from community effort, such as people sharing their thoughts of the BiS, and you choosing what to include in the guides.

The info, I think, should be written as bullet points, with a link to the fully written guide.

**Comment by Eceri** [comment]
There is a recent community effort on discord, collecting guides on everything. I've talked to them, and for now, the decision is to stay on discord. 

discord link: https://discord.gg/Y6fynAy
