### ISSUE TITLE
Notification of updated skins

### ISSUE THREAD

**Issue by KazumaZahka** [Eceri/KR-Index#17]
I don't know if when you comment an issue a notification appears or something similar. If yes I apologize for the bother. Wanted to let you guys know that I've found the honor skins that were missing ^^

**Comment by KazumaZahka** [comment]
![requina](https://user-images.githubusercontent.com/75275150/101269887-bdcc9480-3773-11eb-825d-2ee74b9f1529.png)
![fluss](https://user-images.githubusercontent.com/75275150/101269891-c58c3900-3773-11eb-8b61-e7ede924619b.png)
![ophelia](https://user-images.githubusercontent.com/75275150/101269895-cc1ab080-3773-11eb-9d6a-48ab58204740.png)

**Comment by LLath** [comment]
Hi,
please instead of opening another issue update the old one
