### ISSUE TITLE
Missing skins

### ISSUE THREAD

**Issue by KazumaZahka** [Eceri/KR-Index#18]
Found other missing skins and took screenshots of them

**Comment by KazumaZahka** [comment]
![Screenshot_20201207-122555](https://user-images.githubusercontent.com/75275150/101350916-198c4000-3890-11eb-8017-e7dd15c7fe41.jpg)
![Screenshot_20201207-124105](https://user-images.githubusercontent.com/75275150/101350933-1f822100-3890-11eb-83fd-226c5fab7aa0.jpg)
![Screenshot_20201207-124234](https://user-images.githubusercontent.com/75275150/101350950-25780200-3890-11eb-957f-f08a2ee2f9ef.jpg)
![Screenshot_20201207-124438](https://user-images.githubusercontent.com/75275150/101350980-2c9f1000-3890-11eb-9325-af97cfb8769c.jpg)
![Screenshot_20201207-125511](https://user-images.githubusercontent.com/75275150/101350994-36c10e80-3890-11eb-80ce-33cb0f29cd5e.jpg)
![Screenshot_20201207-130254](https://user-images.githubusercontent.com/75275150/101351016-3cb6ef80-3890-11eb-84cd-7f8203d93bb7.jpg)
![Screenshot_20201207-130527](https://user-images.githubusercontent.com/75275150/101351027-404a7680-3890-11eb-9b43-a911f4f34492.jpg)

**Comment by LLath** [comment]
Hi,
could you please update the other issue instead of creating another one each time ? 
Would be appreciated.
