### ISSUE TITLE
[Outdated] Tanya

### ISSUE THREAD

**Issue by NoManRight** [Eceri/KR-Index#19]
Tanya's Skill 2 Light is no longer "If there is 1 enemy, DMG is increased by 100%.", it has been changed to "Each hit reduces the target's Mana by 300."

Tanya's Skill 3 Dark is no longer "Cooldown is reduced by 5 sec.", it has been changed to "Reduces Mana cost by 1."

Sorry for the trouble.

**Comment by LLath** [comment]
Thanks for letting us know.

We've changed it.
