### ISSUE TITLE
Suggestion about changing link from Plug to kr-official

### ISSUE THREAD

**Issue by arinoki** [Eceri/KR-Index#21]
Right now there is link to plug on top-right, but plug has been closed, so needed to change link to english part of kr-official.com 
![plug-link](https://i.vgy.me/lDpJnC.png)
new link: https://kr-official.community/?page_id=37

**Comment by Eceri** [comment]
ah, right. thanks for pointing that out, I replaced the plug link with https://kr-official.community/
