### ISSUE TITLE
Infernal Gate description is not properly updated when starring.

### ISSUE THREAD

**Issue by Silverawz** [Eceri/KR-Index#24]
**Description with 0 star :**
Increases All DEF by 10%, DMG dealt to enemies by 6%, and DMG dealt to Non-Hero enemies by 6%.

**Description with 5 star :**
Increases All DEF by 25%, DMG dealt to enemies by 6%, and DMG dealt to Non-Hero enemies by 15%.

 DMG dealt to enemies should increase as much as DMG dealt to Non-Hero enemies for every star added.

Great work for the website, really useful!

**Comment by LLath** [comment]
Thanks it should be fixed.

I will close the Issue, you can reopen it if something is still wrong
