### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by KazumaZahka** [Eceri/KR-Index#27]
Can't find the discord server since yesterday. Did something happen to it?

**Comment by LLath** [comment]
Hi, sorry for that inconvenience but I had some problems with discord and it deleted all my channels.

We can create another one if you like.

**Comment by KazumaZahka** [comment]
Sure ^^
Luckily I've saved the pics in a folder for emergencies lol. Once created do you need me to send them all again or nah?

**Comment by LLath** [comment]
Took a while to get to it. But here's the new link: https://discord.gg/BympyXMBaB
Do what you like, both devs don't have much time for krindex right now.
I will close the issue, you can open it again if something is missing.
