### ISSUE TITLE
Prioritise search results for hero names

### ISSUE THREAD

**Issue by gradha** [Eceri/KR-Index#8]
Typing two letters to search for kirze brings up a lot of unexpected results with kirze at the bottom:

![Captura de pantalla 2019-12-31 a las 15 43 06](https://user-images.githubusercontent.com/101927/71681550-476a2a00-2d8d-11ea-93d5-2ed85a9440e4.jpg)

It would be nice if hints were sorted by the index of the matched string, giving priority to lower index positions. This would make kirze appear before other probably less useful partial matches.

**Comment by LLath** [comment]
Now if you search for something it should give you "good" matches like: 
![image](https://user-images.githubusercontent.com/3504160/72274033-b9632e80-362b-11ea-82b1-dc02e0553035.png)

If there is anything you noticed let us know.

**Comment by gradha** [comment]
It seems to work all right for most cases, but for some reason typing the first two letters of Artemia seems to throw it off into the wild until the third letter. See gif:

![arte](https://user-images.githubusercontent.com/101927/72688697-14a08f80-3b0a-11ea-92d3-b21e0a9203c9.gif)

**Comment by LLath** [comment]
It seems like "Artemia" isn't a match for "ar", that's why it shows "Kara" as the most usefull match 🤔 . I`ll look into it a bit more why this happens.
